spring:
    datasource:
        url: jdbc:mysql://localhost:3306/er-sols
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: create
    main:
      banner-mode: "off"